// ISO-3166-1-alpha-2-Codes als kanonischer Speicherwert für media.countries.
// Format: [Code, deutscher Name, englischer Name, weitere bekannte Schreibweisen/Aliase]
const TABLE: [string, string, string, ...string[]][] = [
  ['AD', 'Andorra', 'Andorra'],
  ['AE', 'Vereinigte Arabische Emirate', 'United Arab Emirates', 'UAE'],
  ['AF', 'Afghanistan', 'Afghanistan'],
  ['AG', 'Antigua und Barbuda', 'Antigua and Barbuda'],
  ['AL', 'Albanien', 'Albania'],
  ['AM', 'Armenien', 'Armenia'],
  ['AO', 'Angola', 'Angola'],
  ['AR', 'Argentinien', 'Argentina'],
  ['AT', 'Österreich', 'Austria'],
  ['AU', 'Australien', 'Australia'],
  ['AZ', 'Aserbaidschan', 'Azerbaijan'],
  ['BA', 'Bosnien und Herzegowina', 'Bosnia and Herzegovina'],
  ['BB', 'Barbados', 'Barbados'],
  ['BD', 'Bangladesch', 'Bangladesh'],
  ['BE', 'Belgien', 'Belgium'],
  ['BF', 'Burkina Faso', 'Burkina Faso'],
  ['BG', 'Bulgarien', 'Bulgaria'],
  ['BH', 'Bahrain', 'Bahrain'],
  ['BI', 'Burundi', 'Burundi'],
  ['BJ', 'Benin', 'Benin'],
  ['BN', 'Brunei', 'Brunei'],
  ['BO', 'Bolivien', 'Bolivia'],
  ['BR', 'Brasilien', 'Brazil'],
  ['BS', 'Bahamas', 'Bahamas'],
  ['BT', 'Bhutan', 'Bhutan'],
  ['BW', 'Botsuana', 'Botswana'],
  ['BY', 'Weißrussland', 'Belarus', 'Belarus'],
  ['BZ', 'Belize', 'Belize'],
  ['CA', 'Kanada', 'Canada'],
  ['CD', 'Demokratische Republik Kongo', 'Democratic Republic of the Congo'],
  ['CF', 'Zentralafrikanische Republik', 'Central African Republic'],
  ['CG', 'Republik Kongo', 'Republic of the Congo'],
  ['CH', 'Schweiz', 'Switzerland'],
  ['CI', 'Elfenbeinküste', 'Ivory Coast', "Côte d'Ivoire"],
  ['CL', 'Chile', 'Chile'],
  ['CM', 'Kamerun', 'Cameroon'],
  ['CN', 'China', 'China'],
  ['CO', 'Kolumbien', 'Colombia'],
  ['CR', 'Costa Rica', 'Costa Rica'],
  ['CU', 'Kuba', 'Cuba'],
  ['CV', 'Kap Verde', 'Cape Verde'],
  ['CY', 'Zypern', 'Cyprus'],
  ['CZ', 'Tschechien', 'Czech Republic', 'Czechia', 'Tschechische Republik'],
  ['DE', 'Deutschland', 'Germany'],
  ['DJ', 'Dschibuti', 'Djibouti'],
  ['DK', 'Dänemark', 'Denmark'],
  ['DM', 'Dominica', 'Dominica'],
  ['DO', 'Dominikanische Republik', 'Dominican Republic'],
  ['DZ', 'Algerien', 'Algeria'],
  ['EC', 'Ecuador', 'Ecuador'],
  ['EE', 'Estland', 'Estonia'],
  ['EG', 'Ägypten', 'Egypt'],
  ['ER', 'Eritrea', 'Eritrea'],
  ['ES', 'Spanien', 'Spain'],
  ['ET', 'Äthiopien', 'Ethiopia'],
  ['FI', 'Finnland', 'Finland'],
  ['FJ', 'Fidschi', 'Fiji'],
  ['FR', 'Frankreich', 'France'],
  ['GA', 'Gabun', 'Gabon'],
  ['GB', 'Vereinigtes Königreich', 'United Kingdom', 'UK', 'Great Britain', 'Großbritannien', 'England'],
  ['GE', 'Georgien', 'Georgia'],
  ['GH', 'Ghana', 'Ghana'],
  ['GM', 'Gambia', 'Gambia'],
  ['GN', 'Guinea', 'Guinea'],
  ['GQ', 'Äquatorialguinea', 'Equatorial Guinea'],
  ['GR', 'Griechenland', 'Greece'],
  ['GT', 'Guatemala', 'Guatemala'],
  ['GW', 'Guinea-Bissau', 'Guinea-Bissau'],
  ['GY', 'Guyana', 'Guyana'],
  ['HK', 'Hongkong', 'Hong Kong'],
  ['HN', 'Honduras', 'Honduras'],
  ['HR', 'Kroatien', 'Croatia'],
  ['HT', 'Haiti', 'Haiti'],
  ['HU', 'Ungarn', 'Hungary'],
  ['ID', 'Indonesien', 'Indonesia'],
  ['IE', 'Irland', 'Ireland'],
  ['IL', 'Israel', 'Israel'],
  ['IN', 'Indien', 'India'],
  ['IQ', 'Irak', 'Iraq'],
  ['IR', 'Iran', 'Iran'],
  ['IS', 'Island', 'Iceland'],
  ['IT', 'Italien', 'Italy'],
  ['JM', 'Jamaika', 'Jamaica'],
  ['JO', 'Jordanien', 'Jordan'],
  ['JP', 'Japan', 'Japan'],
  ['KE', 'Kenia', 'Kenya'],
  ['KG', 'Kirgisistan', 'Kyrgyzstan'],
  ['KH', 'Kambodscha', 'Cambodia'],
  ['KP', 'Nordkorea', 'North Korea'],
  ['KR', 'Südkorea', 'South Korea', 'Republic of Korea'],
  ['KW', 'Kuwait', 'Kuwait'],
  ['KZ', 'Kasachstan', 'Kazakhstan'],
  ['LA', 'Laos', 'Laos'],
  ['LB', 'Libanon', 'Lebanon'],
  ['LI', 'Liechtenstein', 'Liechtenstein'],
  ['LK', 'Sri Lanka', 'Sri Lanka'],
  ['LR', 'Liberia', 'Liberia'],
  ['LS', 'Lesotho', 'Lesotho'],
  ['LT', 'Litauen', 'Lithuania'],
  ['LU', 'Luxemburg', 'Luxembourg'],
  ['LV', 'Lettland', 'Latvia'],
  ['LY', 'Libyen', 'Libya'],
  ['MA', 'Marokko', 'Morocco'],
  ['MC', 'Monaco', 'Monaco'],
  ['MD', 'Moldau', 'Moldova'],
  ['ME', 'Montenegro', 'Montenegro'],
  ['MG', 'Madagaskar', 'Madagascar'],
  ['MK', 'Nordmazedonien', 'North Macedonia', 'Republic of North Macedonia', 'Mazedonien', 'Macedonia'],
  ['ML', 'Mali', 'Mali'],
  ['MM', 'Myanmar', 'Myanmar', 'Burma'],
  ['MN', 'Mongolei', 'Mongolia'],
  ['MR', 'Mauretanien', 'Mauritania'],
  ['MT', 'Malta', 'Malta'],
  ['MU', 'Mauritius', 'Mauritius'],
  ['MV', 'Malediven', 'Maldives'],
  ['MW', 'Malawi', 'Malawi'],
  ['MX', 'Mexiko', 'Mexico'],
  ['MY', 'Malaysia', 'Malaysia'],
  ['MZ', 'Mosambik', 'Mozambique'],
  ['NA', 'Namibia', 'Namibia'],
  ['NE', 'Niger', 'Niger'],
  ['NG', 'Nigeria', 'Nigeria'],
  ['NI', 'Nicaragua', 'Nicaragua'],
  ['NL', 'Niederlande', 'Netherlands', 'Holland'],
  ['NO', 'Norwegen', 'Norway'],
  ['NP', 'Nepal', 'Nepal'],
  ['NZ', 'Neuseeland', 'New Zealand'],
  ['OM', 'Oman', 'Oman'],
  ['PA', 'Panama', 'Panama'],
  ['PE', 'Peru', 'Peru'],
  ['PG', 'Papua-Neuguinea', 'Papua New Guinea'],
  ['PH', 'Philippinen', 'Philippines'],
  ['PK', 'Pakistan', 'Pakistan'],
  ['PL', 'Polen', 'Poland'],
  ['PR', 'Puerto Rico', 'Puerto Rico'],
  ['PS', 'Palästina', 'Palestine'],
  ['PT', 'Portugal', 'Portugal'],
  ['PY', 'Paraguay', 'Paraguay'],
  ['QA', 'Katar', 'Qatar'],
  ['RO', 'Rumänien', 'Romania'],
  ['RS', 'Serbien', 'Serbia'],
  ['RU', 'Russland', 'Russia', 'Russian Federation'],
  ['RW', 'Ruanda', 'Rwanda'],
  ['SA', 'Saudi-Arabien', 'Saudi Arabia'],
  ['SD', 'Sudan', 'Sudan'],
  ['SE', 'Schweden', 'Sweden'],
  ['SG', 'Singapur', 'Singapore'],
  ['SI', 'Slowenien', 'Slovenia'],
  ['SK', 'Slowakei', 'Slovakia'],
  ['SL', 'Sierra Leone', 'Sierra Leone'],
  ['SN', 'Senegal', 'Senegal'],
  ['SO', 'Somalia', 'Somalia'],
  ['SR', 'Suriname', 'Suriname'],
  ['SS', 'Südsudan', 'South Sudan'],
  ['SV', 'El Salvador', 'El Salvador'],
  ['SY', 'Syrien', 'Syria'],
  ['SZ', 'Eswatini', 'Eswatini', 'Swaziland'],
  ['TD', 'Tschad', 'Chad'],
  ['TG', 'Togo', 'Togo'],
  ['TH', 'Thailand', 'Thailand'],
  ['TJ', 'Tadschikistan', 'Tajikistan'],
  ['TL', 'Osttimor', 'Timor-Leste'],
  ['TM', 'Turkmenistan', 'Turkmenistan'],
  ['TN', 'Tunesien', 'Tunisia'],
  ['TR', 'Türkei', 'Turkey', 'Türkiye'],
  ['TT', 'Trinidad und Tobago', 'Trinidad and Tobago'],
  ['TW', 'Taiwan', 'Taiwan'],
  ['TZ', 'Tansania', 'Tanzania'],
  ['UA', 'Ukraine', 'Ukraine'],
  ['UG', 'Uganda', 'Uganda'],
  ['US', 'Vereinigte Staaten', 'United States', 'USA', 'United States of America', 'Amerika'],
  ['UY', 'Uruguay', 'Uruguay'],
  ['UZ', 'Usbekistan', 'Uzbekistan'],
  ['VA', 'Vatikanstadt', 'Vatican City'],
  ['VE', 'Venezuela', 'Venezuela'],
  ['VN', 'Vietnam', 'Vietnam'],
  ['XK', 'Kosovo', 'Kosovo'],
  ['YE', 'Jemen', 'Yemen'],
  ['ZA', 'Südafrika', 'South Africa'],
  ['ZM', 'Sambia', 'Zambia'],
  ['ZW', 'Simbabwe', 'Zimbabwe'],
  // Historische Staaten (ISO-3166-3-Übergangscodes): bewusst eigene Einträge,
  // damit sie nicht stillschweigend mit ihrem heutigen Nachfolgestaat verschmolzen werden.
  ['SUHH', 'Sowjetunion', 'Soviet Union', 'USSR', 'UdSSR'],
  ['CSHH', 'Tschechoslowakei', 'Czechoslovakia'],
  ['YUCS', 'Jugoslawien', 'Yugoslavia'],
  ['DDDE', 'Ostdeutschland', 'East Germany', 'German Democratic Republic', 'DDR'],
];
export const COUNTRY_NAME_DE: Record<string, string> = Object.fromEntries(
  TABLE.map(([code, de]) => [code, de]),
);
const ALIAS_TO_CODE: Record<string, string> = {};
for (const [code, de, en, ...aliases] of TABLE)
  for (const alias of [code, de, en, ...aliases]) ALIAS_TO_CODE[alias.toLocaleLowerCase('de')] = code;
export function normalizeCountryToken(raw: string): string {
  const value = raw.trim();
  if (!value) return value;
  return ALIAS_TO_CODE[value.toLocaleLowerCase('de')] || value;
}
export function countryLabel(code: string): string {
  return COUNTRY_NAME_DE[code.toUpperCase()] || code;
}
