export type Media = {
  id: string;
  kind: string;
  title: string;
  original_title: string;
  year: number | null;
  parent_id: string | null;
  parent_title?: string;
  parent_year?: number;
  show_title?: string;
  series_id?: string;
  series_title?: string;
  season: number | null;
  episode: number | null;
  ids: Record<string, string | number>;
  summary: string;
  countries: string[];
  genres: string[];
  directors: string[];
  actors: string[];
  certification: string | null;
  runtime: number | null;
  poster: string | null;
  rating?: number;
  watched_at?: string;
  has_watch?: boolean;
  plex_watched?: boolean;
  seen_evidence?: boolean;
  catalog_checked_at?: string;
  watch_id?: string;
  updated_at: string;
  locked_fields: string[];
  assignment_reason?: string;
  origins?: string[];
  bucket_preference?: string;
};
export type SearchResult = { items: Media[]; hasMore: boolean; elapsed: number };
