'use client';
import { useRouter, useSearchParams } from 'next/navigation';
import { useState, useTransition } from 'react';
import { SlidersHorizontal, LayoutGrid, List } from 'lucide-react';
import { Search } from './search';
import { MediaCard, MediaRow } from './media';
import type { SearchResult } from '@/lib/types';
export function CatalogBrowser({result,privateMode=false}:{result:SearchResult;privateMode?:boolean}) {
 const params=useSearchParams(),router=useRouter(),[pending,start]=useTransition(),[view,setView]=useState('grid');const q=params.get('q')||'',page=Number(params.get('page')||0);
 function navigate(p:URLSearchParams){start(()=>router.push((privateMode?'/data':'/search')+'?'+p));}
 return <><Search key={q} initial={q} compact/><form className="filter-bar" onSubmit={e=>{e.preventDefault();const p=new URLSearchParams();new FormData(e.currentTarget).forEach((v,k)=>{if(v)p.set(k,String(v));});navigate(p);}}><input type="hidden" name="q" value={q}/><label>Typ<select name="type" defaultValue={params.get('type')||'all'}><option value="all">Alle Titel</option><option value="movie">Filme</option><option value="show">Serien</option></select></label><fieldset><legend>Erscheinungsjahr</legend><input aria-label="Erscheinungsjahr von" name="yearFrom" type="number" min="1800" max="2200" placeholder="Von" defaultValue={params.get('yearFrom')||''}/><span>–</span><input aria-label="Erscheinungsjahr bis" name="yearTo" type="number" min="1800" max="2200" placeholder="Bis" defaultValue={params.get('yearTo')||''}/></fieldset>{privateMode&&<><fieldset><legend>Gesehen im Jahr</legend><input aria-label="Anschaujahr von" name="watchedFrom" type="number" min="1900" max="2200" placeholder="Von" defaultValue={params.get('watchedFrom')||''}/><span>–</span><input aria-label="Anschaujahr bis" name="watchedTo" type="number" min="1900" max="2200" placeholder="Bis" defaultValue={params.get('watchedTo')||''}/></fieldset><fieldset><legend>Deine Bewertung</legend><input aria-label="Bewertung von" name="ratingFrom" type="number" min="1" max="10" placeholder="1" defaultValue={params.get('ratingFrom')||''}/><span>–</span><input aria-label="Bewertung bis" name="ratingTo" type="number" min="1" max="10" placeholder="10" defaultValue={params.get('ratingTo')||''}/></fieldset></>}<button className="button" disabled={pending}><SlidersHorizontal size={15}/> Anwenden</button></form><div className="results-heading"><div><h2>{q?`Ergebnisse für „${q}“`:'Im Katalog'}</h2><span className="muted small">{result.items.length} Titel{result.hasMore?' · weitere auf der nächsten Seite':''}{pending?' · wird geladen …':''}</span></div><div className="segmented view-toggle"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="Posteransicht"><LayoutGrid size={17}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="Listenansicht"><List size={17}/></button></div></div><div aria-busy={pending} className={view==='grid'?'poster-grid':'media-list'}>{result.items.map(m=>view==='grid'?<MediaCard item={m} key={m.id}/>:<MediaRow item={m} key={m.id}/>)}</div>{!result.items.length&&<div className="empty"><h3>Kein passender Titel.</h3><p>Versuche einen kürzeren Suchbegriff oder weniger Filter.</p></div>}<div className="pagination"><button className="button" disabled={!page||pending} onClick={()=>{const p=new URLSearchParams(params);p.set('page',String(page-1));navigate(p);}}>← Zurück</button><span>Seite {page+1}</span><button className="button" disabled={!result.hasMore||pending} onClick={()=>{const p=new URLSearchParams(params);p.set('page',String(page+1));navigate(p);}}>Weiter →</button></div></>;
}
