'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Pencil, Save, X, Globe, LockKeyhole } from 'lucide-react';
import type { Media } from '@/lib/types';
async function post(body:unknown){const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).error||'Speichern fehlgeschlagen');}
export function MediaEditor({item}:{item:Media}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();return <><button className="button" onClick={()=>setOpen(!open)}><Pencil size={15}/> Details bearbeiten</button>{open&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Details bearbeiten" className="modal"><div className="section-heading"><h2>Details bearbeiten</h2><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Schließen"><X/></button></div><p className="muted small">Gespeicherte Felder bleiben bei automatischen Metadatenupdates erhalten.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const data:Record<string,unknown>={};for(const k of ['title','original_title','summary','certification'])data[k]=String(form.get(k)||'');for(const k of ['year','runtime'])data[k]=form.get(k)?Number(form.get(k)):null;for(const k of ['countries','genres','directors','actors'])data[k]=String(form.get(k)||'').split(',').map(x=>x.trim()).filter(Boolean);try{await post({action:'media',id:item.id,data});setOpen(false);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="form-grid">{[['title','Titel'],['original_title','Originaltitel'],['year','Erscheinungsjahr'],['runtime','Laufzeit (Minuten)'],['certification','Altersfreigabe'],['countries','Länder, mit Komma getrennt'],['genres','Genres'],['directors','Regie'],['actors','Besetzung (maximal 10)']].map(([key,label])=><label key={key}>{label}<input required={key==='title'} name={key} type={['year','runtime'].includes(key)?'number':'text'} defaultValue={Array.isArray(item[key as keyof Media])?(item[key as keyof Media] as string[]).join(', '):String(item[key as keyof Media]??'')}/></label>)}</div><label>Zusammenfassung<textarea name="summary" rows={6} defaultValue={item.summary}/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="button primary" disabled={busy}><Save size={16}/>{busy?'Speichert …':'Änderungen speichern'}</button></form></section></div>}</>;}
type Review={id:string;body:string;spoiler:boolean;is_public:boolean;parent_source_id?:string;created_at:string};
export function ReviewEditor({review,mediaId}:{review?:Review;mediaId:string}) {const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();return <><button className="text-link" onClick={()=>setOpen(!open)}>{review?<><Pencil size={13}/> Bearbeiten / Sichtbarkeit</>:'＋ Review schreiben'}</button>{open&&<form className="review-form" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await post({action:'review',id:review?.id,mediaId,data:{body:f.get('body'),spoiler:f.get('spoiler')==='on',is_public:f.get('is_public')==='on'}});setOpen(false);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><textarea name="body" rows={7} required maxLength={30000} defaultValue={review?.body} aria-label="Dein Review" placeholder="Was bleibt von diesem Film?"/><label className="checkbox"><input name="spoiler" type="checkbox" defaultChecked={review?.spoiler}/> Enthält Spoiler</label><label className="checkbox"><input name="is_public" type="checkbox" defaultChecked={review?.is_public}/><Globe size={15}/> Öffentlich veröffentlichen — ohne Anschauinformationen</label>{error&&<p className="error">{error}</p>}<button disabled={busy} className="button primary">{busy?'Speichert …':'Review speichern'}</button></form>}</>;}
export function RatingEditor({id,rating}:{id:string;rating:number|null}){const router=useRouter();const [error,setError]=useState('');return <div><label>Deine Bewertung<select aria-label="Deine Bewertung" value={rating??''} onChange={async e=>{try{await post({action:'rating',id,rating:e.target.value?Number(e.target.value):null});router.refresh();}catch(e){setError((e as Error).message);}}}><option value="">Nicht bewertet</option>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{'★'.repeat(i+1)} {i+1}/10</option>)}</select></label>{error&&<p className="error">{error}</p>}</div>;}
export function ReviewBody({review,admin=false}:{review:Review;admin?:boolean}){return <article className="review"><div className="review-meta"><span>Persönliche Perspektive</span>{admin&&<span>{review.is_public?<><Globe size={13}/> Öffentlich</>:<><LockKeyhole size={13}/> Privat</>}</span>}{review.parent_source_id&&<span>Antwort auf einen Kommentar</span>}</div>{review.spoiler?<details><summary>Spoiler anzeigen</summary><p className="review-text">{review.body}</p></details>:<p className="review-text">{review.body}</p>}</article>;}
